#!/bin/bash
echo "Moving /var/log/riak to /var/lib/riak/log to keep on external drive"
mkdir -p /var/lib/riak/log
chown riak:riak /var/lib/riak/log
rm -rf /var/log/riak
ln -s /var/lib/riak/log /var/log/riak
