#!/bin/bash
ip=$(ifconfig | grep 192.168 | cut -d " " -f 10)
for i in {11..15}
  do
    if [ "$ip" != "192.168.0.$i" ]; then
      echo "Sending $1 to 192.168.0.$i"
      scp $1 pi@192.168.0.$i:
    fi
  done
